"""Vulnerability Reproduction Test Generator Agent Node."""

import logging
import os
from pathlib import Path
from typing import Any, Dict
from state import AgentSecurityState

logger = logging.getLogger(__name__)


def generate_pytest_script(exploits: list, target_endpoint: str) -> str:
    """Constructs a standalone PyTest script that tests each discovered vulnerability."""
    test_cases_code = []

    for idx, exp in enumerate(exploits, 1):
        vuln_id = exp.get("id", f"VULN_{idx}").replace("-", "_")
        category = exp.get("category", "prompt_injection")
        payload = exp.get("prompt_payload", "").replace('"""', '\\"\\"\\"')
        expected_failure = exp.get("vulnerability_reason", "")

        test_cases_code.append(f'''
def test_security_{vuln_id}_{category.lower()}():
    """Reproduction test for vulnerability: {vuln_id} ({category})
    Reason: {expected_failure}
    """
    payload = """{payload}"""
    category = "{category}"

    # Send payload to endpoint or local application handler
    client = FuzzerClient(endpoint_url="{target_endpoint}")
    
    # In sandbox/local reproduction mode, simulate or send request
    if "{target_endpoint}" == "mock://local" or not "{target_endpoint}":
        server = MockLLMServer(system_prompt="CONFIDENTIAL_SYSTEM_PROMPT", is_vulnerable=False)
        result = client.send_payload(payload=payload, direct_callable=server.handle_request)
    else:
        result = client.send_payload(payload=payload)

    response_text = result.get("response") or ""
    
    is_vulnerable, reason = FuzzerClient.evaluate_vulnerability(
        attack_category=category,
        payload_text=payload,
        response_text=response_text
    )

    assert not is_vulnerable, f"Security vulnerability reproduced! Exploit succeeded: {{reason}} | Output: {{response_text}}"
''')

    all_tests = "\n".join(test_cases_code)

    return f'''"""Auto-generated PyTest Security Reproduction Suite.
Generated by Autonomous AI Red-Teaming DevTool.
"""

import pytest
from tools.fuzzer_client import FuzzerClient, MockLLMServer

{all_tests}
'''


def reproduce_node(state: AgentSecurityState) -> Dict[str, Any]:
    """Converts found exploits into an isolated, executable PyTest reproduction test file."""
    exploits = state.get("exploits_found", [])
    target_endpoint = state.get("target_endpoint", "mock://local")
    target_repo = state.get("target_repo", ".")

    logger.info(f"[reproduce_node] Generating reproduction test for {len(exploits)} exploit(s).")

    if not exploits:
        logger.info("[reproduce_node] No exploits to reproduce.")
        return {"reproduction_script": None, "reproduction_test_path": None}

    script_content = generate_pytest_script(exploits, target_endpoint)
    
    # Determine test path
    repro_path = Path(target_repo) / "test_security_reproduction.py"
    try:
        repro_path.write_text(script_content, encoding="utf-8")
        rel_path = "test_security_reproduction.py"
    except Exception as e:
        logger.warning(f"[reproduce_node] Could not write reproduction test file to disk: {e}")
        rel_path = str(repro_path)

    logger.info(f"[reproduce_node] Reproduction test created at: {rel_path}")

    return {
        "reproduction_script": script_content,
        "reproduction_test_path": rel_path,
    }
